[package]
name = "slice-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
slicec  = { git = "https://github.com/icerpc/slicec", branch = "main" }
tokio = { version = "1.33.0", features = ["full"] }
tower-lsp = "0.20.0"

[profile.release]
opt-level = "z"
strip = "symbols"
